set MOTIONBUILDER_VERSION=2019
set "MOTIONBUILDER_SDK_PATH=MOTIONBUILDER_SDK_%MOTIONBUILDER_VERSION%"

call set MOTIONBUILDER_LIB_DIR=%%%MOTIONBUILDER_SDK_PATH%%%\lib
call set MOTIONBUILDER_INCLUDE_DIR=%%%MOTIONBUILDER_SDK_PATH%%%\include

echo %MOTIONBUILDER_LIB_DIR%

MeshSync_MotionBuilder.sln
