set MAX_VERSION=2020
set "INCLUDE_VAR=MAX_INCLUDE_DIR_%MAX_VERSION%"
set "LIB_VAR=MAX_LIB_DIR_%MAX_VERSION%"

call set MAX_INCLUDE_DIR=%%%INCLUDE_VAR%%%
call set MAX_LIB_DIR=%%%LIB_VAR%%%
MeshSync_3dsMax.sln
