#pragma once

#include "SceneGraph/msMaterial.h"

namespace ms {

class MaterialManager
{
public:
    MaterialManager();
    ~MaterialManager();
    void clear();
    bool empty() const;
    bool erase(int id);
    MaterialPtr find(int id) const;

    // thread safe
    // material: valid ID must be assigned (assume generated by ResourceIDGenerator<>)
    int add(MaterialPtr material);

    std::vector<MaterialPtr> getAllMaterials();
    std::vector<MaterialPtr> getDirtyMaterials();
    std::vector<Identifier>& getDeleted();
    void makeDirtyAll();
    void clearDirtyFlags();

    std::vector<MaterialPtr> getStaleMaterials();
    void eraseStaleMaterials();

private:
    struct Record
    {
        MaterialPtr material;
        uint64_t checksum = 0;
        bool dirty = false;
        bool updated = false;
    };
    Record& lockAndGet(int id);

    std::map<int, Record> m_records;
    std::vector<Identifier> m_deleted;
    std::mutex m_mutex;
};

} // namespace ms
