start /wait cmd /k "call build_server.bat && exit"
start /wait cmd /k "call build_mq.bat && exit"
start /wait cmd /k "call build_xismo.bat && exit"
start /wait cmd /k "call build_blender.bat && exit"
start /wait cmd /k "call build_maya.bat && exit"
start /wait cmd /k "call build_max.bat && exit"
start /wait cmd /k "call build_motionbuilder.bat && exit"
start /wait cmd /k "call build_vred.bat && exit"
