mklink /J MeshSyncClientMaya2015 MeshSyncClientMaya
mklink /J MeshSyncClientMaya2016 MeshSyncClientMaya
mklink /J MeshSyncClientMaya2016.5 MeshSyncClientMaya
mklink /J MeshSyncClientMaya2017 MeshSyncClientMaya
mklink /J MeshSyncClientMaya2018 MeshSyncClientMaya

mklink /J MeshSyncClientMotionBuilder2015 MeshSyncClientMotionBuilder
mklink /J MeshSyncClientMotionBuilder2016 MeshSyncClientMotionBuilder
mklink /J MeshSyncClientMotionBuilder2017 MeshSyncClientMotionBuilder
mklink /J MeshSyncClientMotionBuilder2018 MeshSyncClientMotionBuilder

mklink /J MeshSyncClientBlender2.79 MeshSyncClientBlender
mklink /J MeshSyncClientBlender2.80 MeshSyncClientBlender
