mkdir "UnityMeshSync for Metasequoia\Metasequoia3"
mkdir "UnityMeshSync for Metasequoia\Metasequoia4 (32bit)"
mkdir "UnityMeshSync for Metasequoia\Metasequoia4 (64bit)"
copy _out\MeshSyncClientMQ3_Win32_Master\MeshSyncClientMQ3.dll "UnityMeshSync for Metasequoia\Metasequoia3"
copy _out\MeshSyncClientMQ4_Win32_Master\MeshSyncClientMQ4.dll "UnityMeshSync for Metasequoia\Metasequoia4 (32bit)"
copy _out\MeshSyncClientMQ4_x64_Master\MeshSyncClientMQ4.dll "UnityMeshSync for Metasequoia\Metasequoia4 (64bit)"
powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::CreateFromDirectory('UnityMeshSync for Metasequoia', 'UnityMeshSync for Metasequoia.zip'); }"
